version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test: 
    docker:
      - image: cimg/python:3.9.8
    steps:
      - checkout
      - run:
          name: List files
          command: |
                   ls -ltra
                   python --version
      - python/install-packages:
          pkg-manager: pip 
      - run:
          name: Run tests
          command: MLFLOW_TRACKING_URI=databricks pytest testing/test_mlflow_projects.py
      - run: 
          name: Print test output
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'


workflows:
  sample: 
    jobs:
      - build-and-test
